feat(prisma): add Prisma adapter
grammyjs/storages pull request #108
Opened 2022-07-20 14:11 UTC by daniharo

Prisma adapter added taking [TypeORM adapter](https://github.com/grammyjs/storages/tree/main/packages/typeorm) as example.

TODO:

- [ ] run tests (can't run because `@grammyjs/storage-utils` doesn't seem to be imported correctly)
- [ ] create PR for grammyjs/website

2022-07-20 14:24 UTC, KnorpelSenf requested changes
Thank you so much!

I'll leave a proper review to @Satont, here's just a short comment about the licensing, as well as a nitpick that lets you drop grammY as a runtime dependency.

2022-07-20 14:24 UTC, KnorpelSenf commented on packages/prisma/LICENSE
> +Copyright (c) 2021 Satont
It's probably good to licence your own code under your own name

2022-07-20 14:24 UTC, KnorpelSenf commented on packages/prisma/src/index.ts
> +import { StorageAdapter } from 'grammy';
```suggestion
import { type StorageAdapter } from 'grammy';
```

2022-07-20 14:42 UTC, KnorpelSenf approved these changes
LGTM, maintainer will merge after reviewing

2022-07-20 15:17 UTC, Satont commented on packages/prisma/src/index.ts
> +import { StorageAdapter } from 'grammy';
Whats difference with `import type { StorageAdapter  }`?

2022-07-20 15:20 UTC, Satont commented
@daniharo can you try build utils manually and then run the tests?

2022-07-20 15:34 UTC, Satont commented
For the tests, you have to call `db push` for prisma, before each of the cases. Can you do this via `exec` so you don't have to do it by hand, I assume?

Also, I think you have to create a new base before each of the cases (delete the old one and create a new one and do the push). You can use `beforeEach` hook from `vitest` package.

2022-07-20 15:40 UTC, Satont commented
Please add adapter to the `packages/README.md` list.

2022-07-20 15:46 UTC, Satont commented
Rebase with master please. I added running tests on PR.

2022-07-20 15:56 UTC, Satont commented
Ok i see tests failed due indepented to pr reasons, so we can ignore that. Just run them manually until i'll fix tests.

2022-07-20 16:24 UTC, daniharo commented
> If you not familiar with tests enough i can fix them myself, if you wan't'

I got the tests working, just have to fix one that fails.

2022-07-20 17:00 UTC, daniharo commented
@Satont I'm getting this error inside the `beforeEach` calls
```
Error: 
Invalid `prisma.session.deleteMany()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })
```

Please check if you can solve it

2022-07-20 17:14 UTC, Satont commented
@daniharo that seems like sqlite database locked. You can use postgres with `pg-mem` like in [psql](https://github.com/grammyjs/storages/blob/main/packages/psql/__tests__/node.ts) storage test instead.

2022-07-20 17:22 UTC, daniharo commented
> @daniharo that seems like sqlite database locked. You can use postgres with `pg-mem` like in [psql](https://github.com/grammyjs/storages/blob/main/packages/psql/__tests__/node.ts) storage test instead.

Prisma needs a connection URL to create the client, I don't think `pg-mem` gives that possibility

2022-07-20 17:28 UTC, Satont commented
> > @daniharo that seems like sqlite database locked. You can use postgres with `pg-mem` like in [psql](https://github.com/grammyjs/storages/blob/main/packages/psql/__tests__/node.ts) storage test instead.
> 
> Prisma needs a connection URL to create the client, I don't think `pg-mem` gives that possibility.
> 
> Gonna try with [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server)

It gives, but you need to run `push` into code, not via cli.

2022-07-20 21:50 UTC, daniharo commented
Tests are now passing.

I just had to add `threads: false` to vitest config in this package to make it work with SQLite (commit https://github.com/grammyjs/storages/pull/108/commits/0dc5550ab41dff242dec30521a1e420c46d5e1a6)

2022-07-21 02:59 UTC, Satont commented
So, it is LGTM except version of package. Can you set it to 2.0.0 to respect other packages?

2022-07-21 03:01 UTC, Satont approved these changes

2022-07-21 11:24 UTC, daniharo commented
I think this is now ready for merging

2022-07-21 11:30 UTC, KnorpelSenf commented
Would you mind updating the docs on the website and linking the pull request here?

2022-07-21 11:44 UTC, daniharo commented
> Would you mind updating the docs on the website and linking the pull request here?

Done

2022-07-21 12:11 UTC, KnorpelSenf commented
Thanks! The website is already updated.

I don't know what the errors in CI are, but I assume that @Satont will know.

2022-07-21 13:31 UTC, merged